### ISSUE TITLE
Tabbar icons are no longer displayed on iOS

### ISSUE THREAD

**Issue by Blamoh** [AathifMahir/MauiIcons#100]
**Describe the bug**
Tabbar icons are no longer displayed on iOS only.

**To Reproduce**
1. Upgrade version to 2.2.5
2. Launch the application
3. Icons are no longer displayed
4. Downgrade to 2.1.5
5. Icons displayed

**Expected behavior**
Icons should be displayed.
**Screenshots**
![image](https://github.com/AathifMahir/MauiIcons/assets/11490937/3f2457d0-9e55-437b-b190-d4a5650271f9)
![image](https://github.com/AathifMahir/MauiIcons/assets/11490937/229017cb-3954-4f18-bf34-969987a215b5)
![image](https://github.com/AathifMahir/MauiIcons/assets/11490937/6dee39ad-bd9f-4fad-a049-17747234e151)

**Smartphone (please complete the following information):**
 - iOS
 - Version 15, 17.2 

**Additional context**
I tested on simulators and on reel phones

**Comment by AathifMahir** [comment]
@Blamoh Have you tested on other platforms other than iOS?

**Comment by Blamoh** [comment]
Hello,
Yes I tested on android, no regression.
for android same on simulator and also on physical device.

the regression only concerns the tabbar. on the page it displays normally.

![image](https://github.com/AathifMahir/MauiIcons/assets/11490937/078eef21-8c11-4df9-896f-b1e7042586ff)

**Comment by AathifMahir** [comment]
> Hello,
> Yes I tested on android, no regression.
> for android same on simulator and also on physical device.
> 
> the regression only concerns the tabbar. on the page it displays normally.
> 
> ![image](https://github.com/AathifMahir/MauiIcons/assets/11490937/078eef21-8c11-4df9-896f-b1e7042586ff)
> 

Seems like a bug within Maui Itself
https://github.com/dotnet/maui/issues/20866

You can find a workaround on the above issue, I assume that would fix your issue

**Comment by Blamoh** [comment]
My current workaround is to stay in version 2.1.5

**Comment by AathifMahir** [comment]
> My current workaround is to stay in version 2.1.5 

@Blamoh check whether v3.0.0 fixes this issue

**Comment by Blamoh** [comment]
unfortunately the same issue.

**Comment by ibrahimmd90** [comment]
It seems like the icons are actually there but in white color. Turn Dark mode on and verify! If so, what would be the workaround?!

**Comment by AathifMahir** [comment]
> It seems like the icons are actually there but in white color. Turn Dark mode on and verify! If so, what would be the workaround?!

Work around is mentioned here
https://github.com/dotnet/maui/issues/20866
