### ISSUE TITLE
Icon binding with MVVM not working

### ISSUE THREAD

**Issue by ricavir11** [AathifMahir/MauiIcons#117]
Icon is not displayed when a binding is applied with MVVM.

ViewModel example :

```
private FontAwesomeSolidIcons _myIcon;
public FontAwesomeSolidIcons MyIcon
{
            get => _myIcon;
            set
            {
                _myIcon = value;
                RaisePropertyChanged(() => MyIcon);
            }
}

public async Task PageAppearingAsync()
{
             MyIcon = FontAwesomeSolidIcons.AddressBook;
}

```

Related view component (Button)

```
<Button    
    Command="{Binding SearchAddressCommand}"
    Text="{mi:FontAwesomeSolid BindingContext={x:Reference HomeViewPage}, Icon={Binding MyIcon}, IconColor={DynamicResource 
   PrimaryColor}, IconSize=25}" />

```

**Comment by ricavir11** [comment]
Yes I will try to provide it soon.
In my current project I'm using MVVM Helpers library but I will provide an example without it.
Nevertheless, it would be interesting to provide a simple sample with MVVM bindings

**Comment by AathifMahir** [comment]
We have made a some improvements to overall binding support with v4 and that makes this no longer issue at all.

Additionally, we are final stage of the release. Stay tuned for v4
