### ISSUE TITLE
Icon binding not working when retrieved from database

### ISSUE THREAD

**Issue by TahaReeh** [AathifMahir/MauiIcons#119]
Icon binding not working when retrieved from database.
I have tried several approaches where I:
- stored the icon names as strings in db.
- stored their values as int from the Enum.
- copied the entire Enum to the domain layer, stored them as Enum. 
- I also saved them as strings and wrote an extension method to convert them at runtime.
None of these methods have worked for me, what am I missing?

The IconSource property is the name of the icon stored in db. as string:
```
modelBuilder.Entity<Category>().HasData(
     Category.Create(
         name: "Food & Drinks",
         nature: CategoryNature.Need,
         **iconSource: "Food24",**
         color: "#ff3d00",
         isVisible: true,
         order: 1
         ),
```
Here is how i use it in XAML:

```
<dx:DXImage x:Name="ImageIcon"
            Source="{mi:Fluent BindingContext={x:Reference model:CreateTransactionVM}, Icon={Binding IconSource}}"
            HeightRequest="20" />
```

**Comment by AathifMahir** [comment]
> Icon binding not working when retrieved from database. I have tried several approaches where I:
> 
> * stored the icon names as strings in db.
> * stored their values as int from the Enum.
> * copied the entire Enum to the domain layer, stored them as Enum.
> * I also saved them as strings and wrote an extension method to convert them at runtime.
>   None of these methods have worked for me, what am I missing?
> 
> The IconSource property is the name of the icon stored in db. as string:
> 
> ```
> modelBuilder.Entity<Category>().HasData(
>      Category.Create(
>          name: "Food & Drinks",
>          nature: CategoryNature.Need,
>          **iconSource: "Food24",**
>          color: "#ff3d00",
>          isVisible: true,
>          order: 1
>          ),
> ```
> 
> Here is how i use it in XAML:
> 
> ```
> <dx:DXImage x:Name="ImageIcon"
>             Source="{mi:Fluent BindingContext={x:Reference model:CreateTransactionVM}, Icon={Binding IconSource}}"
>             HeightRequest="20" />
> ```

Please Try v4 that is Released Few Minutes Ago, Let Us know whether it fixes your issue?
We have Reworked the Whole Data Binding in v4, Most Probably it would fix your issue
