### ISSUE TITLE
Cannot resolve type "http://www.aathifmahir.com/dotnet/2022/maui/icons:mi:MauiIcon"

### ISSUE THREAD

**Issue by PedroLV2001** [AathifMahir/MauiIcons#121]
Hello,

I have tried this <mi:MauiIcon Icon="{mi:FontAwesomeSolid Hashtag}"/> but there is an error on application built:

XamlC error XFC0000: Cannot resolve type "http://www.aathifmahir.com/dotnet/2022/maui/icons:mi:MauiIcon".

I have tried this on the  default MAUI application template adding the following packages:

<PackageReference Include="AathifMahir.Maui.MauiIcons.Core" Version="4.0.0" />
<PackageReference Include="AathifMahir.Maui.MauiIcons.FontAwesome" Version="4.0.0" />
<PackageReference Include="AathifMahir.Maui.MauiIcons.FontAwesome.Brand" Version="4.0.0" />
<PackageReference Include="AathifMahir.Maui.MauiIcons.FontAwesome.Solid" Version="4.0.0" />

setting the MauiProgram.cs :  .UseMauiApp<App>().**UseFontAwesomeSolidMauiIcons**()

and adding the XAML:

 <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.View.MainPage"
             xmlns:model="clr-namespace:MauiApp1.Model"
            xmlns:viewmodel="clr-namespace:MauiApp1.ViewModel"
            x:DataType="viewmodel:MainViewModel"
             xmlns:local="clr-namespace:MauiApp1"
    **xmlns:mi="http://www.aathifmahir.com/dotnet/2022/maui/icons"**>

    <ScrollView>
...

            **<mi:MauiIcon Icon="{mi:FontAwesomeSolid Hashtag}"/>**
.....

I think I didn't miss any configuration step but the XAML compiler cannot find the specified type http://www.aathifmahir.com/dotnet/2022/maui/icons:mi:MauiIcon anyway.

regards

**Comment by PedroLV2001** [comment]
I answer to myseft:

A workarround to solve the issue is to replace the namespaces like this:

instead of xmlns:mi="http://www.aathifmahir.com/dotnet/2022/maui/icons"

 xmlns:**mi**="clr-namespace:MauiIcons.Core;assembly=MauiIcons.Core"
 xmlns:**fs**="clr-namespace:MauiIcons.FontAwesome.Solid;assembly=MauiIcons.FontAwesome.Solid"

and the xaml control :

<**mi**:MauiIcon Icon="{**fs**:FontAwesomeSolid Hashtag}"/>

**Comment by AathifMahir** [comment]
> I answer to myseft:
> 
> A workarround to solve the issue is to replace the namespaces like this:
> 
> instead of xmlns:mi="http://www.aathifmahir.com/dotnet/2022/maui/icons"
> 
> xmlns:**mi**="clr-namespace:MauiIcons.Core;assembly=MauiIcons.Core" xmlns:**fs**="clr-namespace:MauiIcons.FontAwesome.Solid;assembly=MauiIcons.FontAwesome.Solid"
> 
> and the xaml control :
> 
> <**mi**:MauiIcon Icon="{**fs**:FontAwesomeSolid Hashtag}"/>

We have included proper workaround in the docs, you can initiate a discarded instance of MauiIcon in the Code Behind and Use the Url Style Namespace without any issues.

https://github.com/AathifMahir/MauiIcons?tab=readme-ov-file#workaround

**Comment by Lightfire228** [comment]
of particular note, you will still get this error if you forget to initialize the library

https://github.com/AathifMahir/MauiIcons/tree/master/src/MauiIcons.FontAwesome.Solid#get-started

```cs
using MauiIcons.FontAwesome.Solid;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		
		// Initialise the .Net Maui Icons - FontAwesome Solid
		builder.UseMauiApp<App>().UseFontAwesomeSolidMauiIcons();
	}
}
```
