### ISSUE TITLE
Allow Icon Tinting by passing a Tint to the fluent binding

### ISSUE THREAD

**Issue by edgiardina** [AathifMahir/MauiIcons#32]
**Is your feature request related to a problem? Please describe.**
At the moment, Android does not honor the Shell colors when it comes to Toolbar icons. Because of this, I normally have to maintain and tint my SVG icons by hand in order for them to show up right in the toolbar on Android
https://github.com/dotnet/maui/issues/9240

**Describe the solution you'd like**
I would love to be able to provide to the fluent:Icon binding source a Tint property. This way I could declare my ToolbarIcons using a MauiIcons source instead of a standard image source and be able to tint at runtime. This would avoid maintaining multiple sets of icons, and allow further theming and customization at runtime. 
```
<Image Aspect="Center" Source="{fluent:Icon Icon=ActionCenterQuiet, Tint={StaticResource MyColor}"/>
<ToolbarItem Text="Share" x:Name="ShareButton" Clicked="ShareButton_Clicked" 
    IconImageSource="{fluent:Icon Icon=ActionCenterQuiet, Tint={StaticResource MyColor}" />
```
It would also be nice if the tint could take an AppThemeBinding
`{AppThemeBinding Light={StaticResource PrimaryTextColor}, Dark={StaticResource PrimaryTextColorDark}}`
So that I could tint differently depending on Dark Mode / Theme.

**Comment by AathifMahir** [comment]
@edgiardina Will implement this as soon as possible

**Comment by AathifMahir** [comment]
@edgiardina Can you please provide a simple sample based on this scenario, as far as my testing i don't have any issues on showing icons with color on android with MauiIcons

**Comment by edgiardina** [comment]
There's already an IconColor?! I mean, I think that means MauiIcons already supports what I want to do. Thank you!!!!!

**Comment by AathifMahir** [comment]
> There's already an IconColor?! I mean, I think that means MauiIcons already supports what I want to do. Thank you!!!!!

Thanks for confirmation, will close this issue
