### ISSUE TITLE
Add Round, Outlined and TwoTone Support for Material Icons Module

### ISSUE THREAD

**Issue by AathifMahir** [AathifMahir/MauiIcons#47]
Add Round, Outlined, Sharp and TwoTone Support for Material Icons Module by Adding Needed .ttf or .otf font files and Update the Material Icons Enumeration to Include Those Icons as Well

Edit: TwoTone Version going to be removed  and other variants going to stay,

The TwoTone Version has the problem of rendering on a single color and manipulating color doesn't work with the TwoTone version. This might be related to Maui Font Rendering or The TwoTone Font itself. Therefore we made the decision on removing the TwoTone Variant Altogether.

**Comment by AathifMahir** [comment]
@vhugogarcia Do we really need TwoTone Icons Support on Material Icons, As far as Current Testing The TwoTone Version has Limitation with Coloring, The TwoTone Just Stays Black Even Explicity Coloring The Icons or Fonts, I guess this has do with limitation of Font Renderer of Maui or The Font Itself

**Comment by vhugogarcia** [comment]
Hello @AathifMahir, I think we can skip it for now and revisit it in the future is somebody asks about it. I agree with you.
