### ISSUE TITLE
FontAwesome support

### ISSUE THREAD

**Issue by realZhangChi** [AathifMahir/MauiIcons#57]
Hello, this is a great project, can you integrate font Awesome?

**Comment by AathifMahir** [comment]
> Hello, this is a great project, can you integrate font Awesome?

Can you specify which version of font awesome icons you're looking for etc..

**Comment by realZhangChi** [comment]
@AathifMahir Sorry for the late reply, fontawesom 6 free version is fine。

**Comment by AathifMahir** [comment]
> @AathifMahir Sorry for the late reply, fontawesom 6 free version is fine。

Thanks for the reply, I will look into Fontawesome6 Icons
