### ISSUE TITLE
SwipeView.SwipeItem.IconImageSource IconColor and IconBackgroundColor does not affect the appearance of the icon

### ISSUE THREAD

**Issue by uom42** [AathifMahir/MauiIcons#86]
**Describe the bug**
SwipeView.SwipeItem.IconImageSourceЖ
IconColor and IconBackgroundColor properties does not affect the appearance of the icon

**To Reproduce:**

```
<SwipeView>
	<SwipeView.LeftItems>
		<SwipeItems>

			<SwipeItem>
				<SwipeItem.IconImageSource>
					<mi:MaterialOutlined
						Icon="Edit"
						IconBackgroundColor="Magenta"
						IconColor="Green" />
					</SwipeItem.IconImageSource>
				</SwipeItem>

				<SwipeItem				
				IconImageSource="{mi:MaterialOutlined Icon=Delete,
				                                      IconColor=Red}" />
			</SwipeItems>
	</SwipeView.LeftItems>

</SwipeView>
```

Light Mode:
![Light](https://github.com/AathifMahir/MauiIcons/assets/6280840/f87b797f-613a-4190-a097-4451739b2f38)

DarkMode:
![Dark](https://github.com/AathifMahir/MauiIcons/assets/6280840/b94f0e02-a056-45a7-b4dc-09562a701e3c)

**Expected behavior**
Icons must respect the specified colors

**Smartphone:**
Additional context
API33 Android 13.0
net8.0-android

**Comment by AathifMahir** [comment]
> **Describe the bug** SwipeView.SwipeItem.IconImageSourceЖ IconColor and IconBackgroundColor properties does not affect the appearance of the icon
> 
> **To Reproduce:**
> 
> ```
> <SwipeView>
> 	<SwipeView.LeftItems>
> 		<SwipeItems>
> 
> 			<SwipeItem>
> 				<SwipeItem.IconImageSource>
> 					<mi:MaterialOutlined
> 						Icon="Edit"
> 						IconBackgroundColor="Magenta"
> 						IconColor="Green" />
> 					</SwipeItem.IconImageSource>
> 				</SwipeItem>
> 
> 				<SwipeItem				
> 				IconImageSource="{mi:MaterialOutlined Icon=Delete,
> 				                                      IconColor=Red}" />
> 			</SwipeItems>
> 	</SwipeView.LeftItems>
> 
> </SwipeView>
> ```
> 
> Light Mode: ![Light](https://private-user-images.githubusercontent.com/6280840/310119921-f87b797f-613a-4190-a097-4451739b2f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzMwMDIsIm5iZiI6MTcwOTg3MjcwMiwicGF0aCI6Ii82MjgwODQwLzMxMDExOTkyMS1mODdiNzk3Zi02MTNhLTQxOTAtYTA5Ny00NDUxNzM5YjJmMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDQzODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJlOGZlZmY3MzdkZDViZTZlNDRkNzEwNGQ5YmUzYTNjMGJhODM3YmQzNTRmYTViMDMzYjc3MzVmYTk3NjM1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sxR6zbnWY77sa4Fu4R98413PkFgd2J_95XpNEI43Rak)
> 
> DarkMode: ![Dark](https://private-user-images.githubusercontent.com/6280840/310119945-b94f0e02-a056-45a7-b4dc-09562a701e3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzMwMDIsIm5iZiI6MTcwOTg3MjcwMiwicGF0aCI6Ii82MjgwODQwLzMxMDExOTk0NS1iOTRmMGUwMi1hMDU2LTQ1YTctYjRkYy0wOTU2MmE3MDFlM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDQzODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDExZWYzOWI1YTYzN2M2NWM4Yzg5ZjkxNDJiMzE1NjYyMTFhNTE1ZjJjZTcyYjU0OGVjNTA0ZTQ2YWEwYmU3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KV3U76dW0OXsC0tNQWnMzpsYDAuciseIccluCwVMqg0)
> 
> **Expected behavior** Icons must respect the specified colors
> 
> **Smartphone:** Additional context API33 Android 13.0 net8.0-android

As far as My Testing on this Use Case, I Found that Even If we pass a custom Image Source to SwipeItem with Different Color Property Which Isn't White, The SwipeItem Still Overrides the Image Source Color to Be Black or White Based on AppTheme, On  my understanding this should be limitation that applied by Maui Itself or a Bug in Maui

**Comment by AathifMahir** [comment]
@uom42 I'm closing this issue, if you have any further questions, feel free to comment on this issue.
