### ISSUE TITLE
Crash on startup (version 2.1.1)

### ISSUE THREAD

**Issue by AntunTkalcec** [AathifMahir/MauiIcons#87]
**Describe the bug**
The bug is caused by version 2.1.1 and crashes the app at startup.

**To Reproduce**
1. Install version 2.1.1
2. Build and deploy the app to an Android smartphone
3. Start the app
4. Crash during splash-screen

**Expected behavior**
The app starts.

**Screenshots**

**Desktop and Smartphone (please complete the following information):**
 - OS: Android (OxygenOS 14.0)
 - Version: Android 14

**Additional context**
The problem is caused on version 2.1.1. 'adb logcat' had this to say:
"Assertion at ..., condition 'is_ok (error)' not met, function: decode_path, module **'myapp.dll.so' is unusable (GUID of dependent assembly MauiIcons.FontAwesome.Solid doesn't match...**"

The only fix is downgrading to 2.1.0.

**Comment by AathifMahir** [comment]
> **Describe the bug**
> The bug is caused by version 2.1.1 and crashes the app at startup.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Install version 2.1.1
> 2. Build and deploy the app to an Android smartphone
> 3. Start the app
> 4. Crash during splash-screen
> 
> **Expected behavior**
> The app starts.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop and Smartphone (please complete the following information):**
>  - OS: Android (OxygenOS 14.0)
>  - Version: Android 14
> 
> **Additional context**
> The problem is caused on version 2.1.1. 'adb logcat' had this to say:
> "Assertion at ..., condition 'is_ok (error)' not met, function: decode_path, module **'myapp.dll.so' is unusable (GUID of dependent assembly MauiIcons.FontAwesome.Solid doesn't match...**"
> 
> The only fix is downgrading to 2.1.0.
> 

Let me try to reproduce this issue

**Comment by AathifMahir** [comment]
@AntunTkalcec I might need more information on this. Is this issue only happens on Font awesome Solid Icons? Had a chance to test it on different module?

**Comment by AntunTkalcec** [comment]
Yes, I only tried the Solid module. Happened on multiple devices as soon as I updated to 2.1.1, and did not occur again after I downgraded to 2.1.0. Tried uninstalling and installing again (with 2.1.1) and the error still happened.

**Comment by AntunTkalcec** [comment]
Clicked to complete the issue by accident.

**Comment by AathifMahir** [comment]
> Yes, I only tried the Solid module. Happened on multiple devices as soon as I updated to 2.1.1, and did not occur again after I downgraded to 2.1.0. Tried uninstalling and installing again (with 2.1.1) and the error still happened. 

Thanks for the update on the issue, will patch this issue as soon as possible.

**Comment by AathifMahir** [comment]
@AntunTkalcec Does this issue Happened on Dotnet 7 or 8?

**Comment by AntunTkalcec** [comment]
Net8.
If you can't reproduce, maybe it happens due to an interaction with other NuGets? I don't see how that would be the case, but I don't know... 

If you think it's possible, I'll provide you with what other packages I'm using.

**Comment by AathifMahir** [comment]
> Net8.
> If you can't reproduce, maybe it happens due to an interaction with other NuGets? I don't see how that would be the case, but I don't know... 
> 
> If you think it's possible, I'll provide you with what other packages I'm using. 

I don't think having other nugets would cause this issue, by the way can you try building MauiIcons sample app and try?

**Comment by AathifMahir** [comment]
@AntunTkalcec Any update on this issue? Also released a new version of MauiIcons Tonight with Updated Maui Dependencies, Feel free to try whether the latest version fixes your issue.

**Comment by AntunTkalcec** [comment]
Seems to be fine now, using AathifMahir.Maui.MauiIcons.FontAwesome.Solid 2.1.2 and Microsoft.Maui.Controls & Microsoft.Maui.Controls.Compatibility versions 8.0.10.

I'm pretty sure there was a mismatch between the Maui NuGets my app was using and the versions your NuGet was using. Though I can't be sure if that was what was causing the issue.

**Comment by AathifMahir** [comment]
> Seems to be fine now, using AathifMahir.Maui.MauiIcons.FontAwesome.Solid 2.1.2 and Microsoft.Maui.Controls & Microsoft.Maui.Controls.Compatibility versions 8.0.10.
> 
> I'm pretty sure there was a mismatch between the Maui NuGets my app was using and the versions your NuGet was using. Though I can't be sure if that was what was causing the issue. 

I'll close this issue for now, feel free to reopen if you found facing this issue again
