### ISSUE TITLE
Allow Icon Animation on demand 

### ISSUE THREAD

**Issue by kmvickers** [AathifMahir/MauiIcons#93]
You allow animation on appearance .. but woudl be good to allow the animation on demand .. for instance if I put an icon on a button or tab .. then shake the icon when the button is pressed

**Comment by AathifMahir** [comment]
> You allow animation on appearance .. but woudl be good to allow the animation on demand .. for instance if I put an icon on a button or tab .. then shake the icon when the button is pressed 
> 

Yeah, that would be super cool. Let me prototype possible implementation of this in coming months.
